# Generated by Django 2.2.6 on 2020-08-10 00:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200809_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='endDate',
            field=models.DateField(default=datetime.datetime(2020, 9, 9, 0, 48, 56, 583078, tzinfo=utc)),
        ),
    ]
